feat(API): new TableOfContents using Mosaic
stoplightio/elements pull request #1084
Opened 2021-04-18 02:05 UTC by lottamus

**No rush to merge this PR before the API early access release**

There's only a couple things left, so I'm hoping for some early feedback. Happy to hop on a call to walk through the changes too!

## What's in this PR?
- Add a new TableOfContents component using Mosiac
- Rework how we compute OAS nodes to have better typings
- Add a simple loading spinner while we're fetching the API document
- Add fallback to operationId when no summary (fixes https://github.com/stoplightio/elements/issues/1056)
- Tests we're not breaking tag names (fixes #829)

## What's left to do on this PR?
- [x] Add fallback endpoint name: https://github.com/stoplightio/elements/issues/1056
- [x] Fix integration tests

## What are you doing in a different PR?
- Fix icon colors (needs an update to mosaic)
- Add strike through styling for deprecated operations
- Update DevPortal component to use new Mosaic TableOfContents
- Remove old UI-Kit TableOfContents

## Questions

- We're [no longer capitalizing tags](https://github.com/stoplightio/elements/issues/829), but the Zoom API's tags are all lower case. Maybe we should only capitalize a tag if we detect it's all lowercase? 🤷 
- What do we think about moving the "API" container/component into `/components/API/index.ts`? Eventually I think we want to get rid of the `containers` directory

## Screenshots

**Design**

![image](https://user-images.githubusercontent.com/7423098/115131857-d15cf700-9fc0-11eb-8957-e1182f7007d2.png)

**Before**

![image](https://user-images.githubusercontent.com/7423098/115131865-e89be480-9fc0-11eb-9d99-129674d7987b.png)

**After**

![image](https://user-images.githubusercontent.com/7423098/115132785-eb023c80-9fc8-11eb-9ebd-9c9a585cf584.png)

2021-04-20 09:03 UTC, mpodlasin reviewed
Remember to test our `examples` as well.

`angular` is a good test, because it uses web components version.

`gatsby` is a good test, because it uses (a variant of) SSR.

![Screenshot from 2021-04-20 11-02-34](https://user-images.githubusercontent.com/7916523/115369072-071ffc80-a1c8-11eb-8eca-9ed7add78797.png)

I am done with review now. In general I like the changes - most of my comments are really minor issues.

2021-04-20 12:05 UTC, marcelltoth requested changes
Thank you for the contribution @lottamus! 

There's a lot of different things going on here, is there any chance you can break this up into multiple PRs? 

I know your workflow with mosaic is a little different but we tend to take the "1 logical change per PR" rule seriously. Your description lists 5 different work items, all of which are great, but viewing them as a single +1300-600 mass makes it really hard to reason about your changes.

While I understand that the TOC itself is hard to break up, there are some obvious ones that we could extract, like the #1056 fix, that is totally unrelated to the PR anyway. (We could ship the fix quickly while we discuss the rest of the changes here.

Also, I am in the process of reviewing the code still, but: Is there any chance you could ship the new TOC first, without breaking the signature and performing the `uriMap` cleanup, then make it nicer later? (Which is great and something I meant to do for a while actually, see #867 ) That would make the review of this much much simpler IMO.

Also please add a storybook entry and follow the [testing guidelines](https://github.com/stoplightio/elements/blob/main/CONTRIBUTING.md) for all the issues that you fix and new code you write (this includes the new ToC).

2021-04-21 23:13 UTC, lottamus commented on packages/elements/src/components/API/SidebarLayout.tsx
> +  if ((isOverview && !hasOverview) || !node) {
Addressed this in https://github.com/stoplightio/elements/pull/1110

2021-04-21 23:14 UTC, lottamus commented on packages/elements/src/components/API/utils.ts
> +export const computeTagGroups = (serviceNode: ServiceNode, childNodes: ServiceChildNode[]) => {
Added `serviceNode.children` in https://github.com/stoplightio/elements/pull/1109

2021-04-21 23:14 UTC, lottamus commented on packages/elements/src/components/MosaicTableOfContents/TableOfContents.tsx
> +  } else if (isNodeGroup(item)) {
Removed the extra case in https://github.com/stoplightio/elements/pull/1110

2021-04-21 23:14 UTC, lottamus commented on packages/elements/src/components/MosaicTableOfContents/TableOfContents.tsx
> +export const TableOfContents = React.memo<TableOfContentsProps>(({ tree, activeId, Link }) => {
Added a storybook in https://github.com/stoplightio/elements/pull/1110 🤓

2021-04-21 23:15 UTC, lottamus commented on packages/elements/src/components/MosaicTableOfContents/utils.ts
> +const MAX_DEPTH_OPEN_BY_DEFAULT = 0; // Maximum group depth open by default
Let's wait to add the prop later if we decide it's necessary

2021-04-21 23:15 UTC, lottamus commented on packages/elements/src/components/MosaicTableOfContents/utils.ts
> +// Recursively checks for the active idem
Ha nice, fixed the typo in https://github.com/stoplightio/elements/pull/1110

2021-04-21 23:16 UTC, lottamus commented on packages/elements/src/components/API/utils.ts
> +export const computeAPITree = (serviceNode: ServiceNode, childNodes: ServiceChildNode[]) => {
The API TOC is actually really simple now: https://github.com/stoplightio/elements/pull/1110/files#diff-46e8533247639f8e0dd666c48d0fa951feb99d6860177e4fea88ddf87ad7310bR54

2021-04-21 23:16 UTC, lottamus commented on packages/elements/src/components/API/utils.ts
> +export const computeAPITree = (serviceNode: ServiceNode, childNodes: ServiceChildNode[]) => {
The API TOC is actually really simple now: https://github.com/stoplightio/elements/pull/1110/files#diff-46e8533247639f8e0dd666c48d0fa951feb99d6860177e4fea88ddf87ad7310bR54

2021-04-21 23:17 UTC, lottamus commented
@marcelltoth @mpodlasin I've split this PR into two in hopes it's easier to review 🙏 . I'll close this one in favor of those:

1. https://github.com/stoplightio/elements/pull/1109
2. https://github.com/stoplightio/elements/pull/1110

2021-04-21 23:17 UTC, closed without merging

2021-04-22 02:03 UTC, marbemac commented
> Also please add a storybook entry and follow the testing guidelines for all the issues that you fix and new code you write (this includes the new ToC).

@marcelltoth I'm not against tests obv.. see mosaic for dozens of frontend tests.. but Is this requirement to add tests something we're just starting now with this PR or is this a standard your team has been enforcing over the last 6 months?

2021-04-22 09:26 UTC, marcelltoth commented
Thank you @lottamus, It's much simpler this way! I'll make sure to review them both today!

> 
> 
> > Also please add a storybook entry and follow the testing guidelines for all the issues that you fix and new code you write (this includes the new ToC).
> 
> @marcelltoth I'm not against tests obv.. see mosaic for dozens of frontend tests.. but Is this requirement to add tests something we're just starting now with this PR or is this a standard your team has been enforcing on additions/fixes/etc over the last 6 months?

I'm not penalizing you specifically or anything of course 🙂 , it's been the way we work for a long time. I can happily offer our help with writing them if you need any assistance. Just message us on Slack with questions or even ask us to write some for you.