chore(release): elements-core v7.1.0
stoplightio/elements pull request #1529
Opened 2021-07-01 15:07 UTC by mmiask

Needed for: https://github.com/stoplightio/platform-internal/issues/6253

2021-07-02 12:34 UTC, marcelltoth requested changes

2021-07-02 12:34 UTC, marcelltoth commented on packages/elements-dev-portal/package.json
> +    "@stoplight/elements-core": "~7.0.0",
Can we enforce >= 7.0.1 here? According to our best knowledge 7.0.0 does **not** work, so would you make this `~7.0.1` instead? Same for `elements`.

2021-07-02 13:24 UTC, marcelltoth approved these changes
You're right, it's not 7.0.1 but 7.1.0. Looks great now, thank you!

2021-07-02 13:50 UTC, merged

2021-07-05 09:13 UTC, mpodlasin reviewed
LGTM

2021-07-05 09:13 UTC, mpodlasin commented
Lol, I thought it's still open for some reason :D