chore(docs): add guide for using dev portal with angular
stoplightio/elements pull request #2119
Opened 2022-04-18 16:08 UTC by pamgoodrich

Added Angular setup for Elements Dev Portal.

2022-04-25 20:15 UTC, pamgoodrich commented
@lottamus: Can you please take a look at this issue so we can get it merged? I can also ask someone on Tacocat to take a look. Let me know.

2022-04-25 20:23 UTC, lottamus requested changes
Looks good, but need to use the correct web component name

2022-04-25 20:23 UTC, lottamus commented on docs/getting-started/dev-portal/dev-portal-angular.md
> +></elements-dev-portal-api>
```suggestion
<elements-stoplight-project
  projectId="cHJqOjQxODY"
  basePath="/api-reference"
></elements-stoplight-project>
```

2022-04-26 16:37 UTC, lottamus approved these changes
Two small changes then it's good to go

2022-04-26 16:52 UTC, pamgoodrich commented on docs/getting-started/dev-portal/dev-portal-angular.md
> +   basePath="/api-reference"
Done

2022-04-26 16:52 UTC, pamgoodrich commented on docs/getting-started/dev-portal/dev-portal-angular.md
> +Notice we added a `basePath` to our API component? We'll also want to add a route for the `/your-html-file` path in our `app-routing.module.ts` file. It's important that we also add a catch-all route
Oh! Thank you! I started to change the example then changed my mind. I missed changing this back.

2022-04-26 17:15 UTC, merged