fix(elements-core): make sidebar resizable
stoplightio/elements pull request #2268
Opened 2022-10-25 07:19 UTC by porotkin

# Feature: Resizable Sidebar

I consider that it'd be better if a user could resize the sidebar to fit his needs.
I need this functionality myself, so I'd be glad if you take a look at my PR, @Amjcraft

Thank you! 

In general, make sure you have: (check the boxes to acknowledge you've followed this template)

- [ ] Read [`CONTRIBUTING.md`](../CONTRIBUTING.md)

#### Other Available PR Templates:

- Release: https://github.com/stoplightio/elements/compare?template=release.md
  - [ ] [Read the release section of `CONTRIBUTING.md`](../CONTRIBUTING.md#releasing-elements)

2022-10-25 07:33 UTC, aerialist7 requested changes

2022-10-25 07:33 UTC, aerialist7 commented on packages/elements-core/src/hooks/useResizer.ts
> +export function useResizer(sidebarWidth: number): [React.Ref<HTMLDivElement>, number, (event: any) => void] {
Seems this hook consider only to `SidebarLayout` component and should be private

2022-10-25 07:33 UTC, aerialist7 commented on packages/elements-core/src/hooks/useResizer.ts
> +export function useResizer(sidebarWidth: number): [React.Ref<HTMLDivElement>, number, (event: any) => void] {
What about type aliases?

2022-10-25 07:33 UTC, aerialist7 commented on packages/elements-core/src/hooks/useResizer.ts
> +  const sidebarRef = useRef<HTMLDivElement | null>(null);
You are using `React.` prefix somewhere.
But here - don't.

Seems you need to align the approach

2022-10-25 10:44 UTC, porotkin commented
@P0lip, please, take a loot at the changes. I have accidentally removed the request for you

2022-10-25 12:08 UTC, aerialist7 approved these changes

2022-10-26 11:17 UTC, P0lip commented
Thanks for the PR! I'll take a look at it shortly.

2022-10-27 11:21 UTC, P0lip reviewed
Looks good overall. Nice work. Thank you!

2022-10-27 11:21 UTC, P0lip commented on packages/elements-core/src/core.css
> +
```suggestion

```

2022-10-27 11:21 UTC, P0lip commented on packages/elements-core/src/components/Layout/SidebarLayout.tsx
> +          onMouseDown={(e: { preventDefault: () => void }) => e.preventDefault()}
```suggestion
          onMouseDown={(e: React.MouseEvent<HTMLElement>) => e.preventDefault()}
```

2022-10-27 11:21 UTC, P0lip commented on packages/elements-core/src/components/Layout/SidebarLayout.tsx
> +          direction="row"
```suggestion
```
that's already a default, isn't it?

2022-10-27 11:21 UTC, P0lip commented on packages/elements-core/src/components/Layout/SidebarLayout.tsx
> +    window.addEventListener('mouseup', stopResizing);
```suggestion
    window.addEventListener('mouseup', stopResizing, { passive: true });
```
could be passive

2022-10-27 12:33 UTC, porotkin commented
Thanks for the tips and suggestions! I've merged 'em all. It seems that the CI is failing but the reason is not related to the changes (it cannot download tslib somehow)

2022-10-27 16:56 UTC, aerialist7 approved these changes

2022-11-02 07:02 UTC, P0lip approved these changes
Thank you!

2022-11-02 07:22 UTC, porotkin commented
@P0lip, thanks for the guidance :)

By the way, could you, please, take a glance on https://github.com/stoplightio/elements/issues/2253? We'd really appreciate any recommendation/workaround/tip regarding this matter.

And currently I am looking into AsyncApi rendering support in @stoplight/elements. I wrote a comment https://github.com/stoplightio/elements/issues/1766#issuecomment-1290277109. If it's of interest to you, I'd be glad to receive any feedback. Currently, I've made some progress transforming AsyncApi specification into ServiceNode and rendered Streetlight Kafka API:
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/34237389/199425168-e492d6cb-3e0c-4ac3-a22e-9a01aae20a00.png">

2022-11-03 17:26 UTC, P0lip commented
#2253 is probably due to us trying to create a regular expression out of it.
We use `.match` somewhere and that could explain. I believe one can just use `includes` in there.

By the way, could you make the gutter a bit wider? It's a bit difficult to hit right now.

2022-11-03 17:45 UTC, mnaumanali94 commented
Thanks @porotkin for this! In addition to what Jakub said, i think the resizing could use a smaller limit in order to not let people mess up the layout

2022-11-09 15:49 UTC, porotkin commented
Thanks, @P0lip and @mnaumanali94, I have enlarged the resizer to 1em instead of 1px and set the bounds for currentSidebarWidth property. Hopefully, this is what you wanted to see.

2022-11-15 15:46 UTC, merged

2022-11-15 15:46 UTC, P0lip commented
Thank you!