fix: Fix Leading / in Empty Paths Rendering for Elements View
stoplightio/elements pull request #2745
Opened 2024-11-29 07:00 UTC by lukasikp

# Elements Default PR Template

In general, make sure you have: (check the boxes to acknowledge you've followed this template)

- [ ] Read [`CONTRIBUTING.md`](../CONTRIBUTING.md)

#### Other Available PR Templates:

- Release: https://github.com/stoplightio/elements/compare?template=release.md
  - [ ] [Read the release section of `CONTRIBUTING.md`](../CONTRIBUTING.md#releasing-elements)

2024-12-02 08:26 UTC, darekplawecki requested changes

2024-12-02 08:26 UTC, darekplawecki commented on packages/elements/package.json
> -  "version": "8.5.0",
You need to bump up the `elements-core` version in the dependencies here and in `elements-dev-portal` as well.

2024-12-03 08:45 UTC, darekplawecki approved these changes

2024-12-03 09:02 UTC, ben-smartbear approved these changes

2024-12-04 08:41 UTC, merged

2024-12-18 10:13 UTC, guillaume-alvarez commented
Thanks!
I just stumbled on the same bug and was looking how to fix it.